spring.application.name=SportsFacilities-system-booking
server.port=4040
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/sportsFacilities_db}
spring.datasource.username=${DB_USERNAME:boss}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG
upload.dir=uploads

# JWT
app.jwt.secret=${JWT_SECRET:843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3}

# Default Admin Seed
app.admin.email=${ADMIN_EMAIL:admin@gmail.com}
app.admin.password=${ADMIN_PASSWORD:admin123}




